[package]
name = "egui_three_d_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.23.0", features = ["glow"]}
env_logger = "0.10.0"
three-d = "0.16.2"
